version: '3.9'
services:
  sftp:
    image: atmoz/sftp
    volumes:
        - ./upload:/home/spring/upload
    ports:
        - "2222:22"
    command: spring:password:::upload
    networks:
      - sftp_network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    networks:
      - sftp_network
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    networks:
      - sftp_network
networks:
  sftp_network:
    driver: bridge